# Generated by Django 3.0 on 2019-12-11 22:31

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('webscraper', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScrapedUrlData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_start', models.DateTimeField(default=None, null=True)),
                ('date_end', models.DateTimeField(default=None, null=True)),
                ('path', models.TextField(default='/home/maciej/Desktop/semantive/Semantive/scraperservice/scraped_url')),
                ('status', models.CharField(choices=[('NS', 'not started'), ('IP', 'in progress'), ('FD', 'finished')], default='NS', max_length=2)),
                ('type', models.CharField(choices=[('t', 'text'), ('i', 'images')], max_length=1)),
            ],
        ),
        migrations.RemoveField(
            model_name='scrapedurltext',
            name='Scraped_url',
        ),
        migrations.AddField(
            model_name='scrapedurl',
            name='date_init_request',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='scrapedurl',
            name='queue',
            field=models.TextField(default='test'),
        ),
        migrations.DeleteModel(
            name='ScrapedUrlImages',
        ),
        migrations.DeleteModel(
            name='ScrapedUrlText',
        ),
        migrations.AddField(
            model_name='scrapedurldata',
            name='url',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webscraper.ScrapedUrl'),
        ),
    ]
