# Generated by Django 3.0 on 2019-12-23 14:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webscraper', '0006_auto_20191219_2034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='queuetask',
            name='queue',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='webscraper.Queue'),
        ),
        migrations.AlterField(
            model_name='queuetaskstatus',
            name='name',
            field=models.TextField(choices=[('PENDING', 'Pending'), ('RECEIVED', 'Received'), ('STARTED', 'Started'), ('SUCCESS', 'Success'), ('FAILURE', 'Failure'), ('REVOKED', 'Revoked'), ('RETRY', 'Retry')], unique=True),
        ),
        migrations.AlterField(
            model_name='scrapedurl',
            name='task',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='webscraper.QueueTask'),
        ),
        migrations.AlterField(
            model_name='urlcontenttype',
            name='name',
            field=models.TextField(choices=[('text', 'Text'), ('images', 'Images'), ('recursive_url', 'Recursive Url')], unique=True),
        ),
    ]
