# Generated by Django 3.0 on 2019-12-30 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webscraper', '0007_auto_20191223_1507'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scrapedurl',
            name='type',
        ),
        migrations.AddField(
            model_name='scrapedurl',
            name='content_type',
            field=models.ManyToManyField(to='webscraper.UrlContentType'),
        ),
    ]
